### ISSUE TITLE
finite depracated?

### ISSUE THREAD

**Issue by mcoughlin** [astromatic/psfex#12]
When compiling on my Mac, I see:

Making all in levmar
gcc -DHAVE_CONFIG_H -I. -I../..    -D_REENTRANT   -g -O2 -MT lmbc.o -MD -MP -MF .deps/lmbc.Tpo -c -o lmbc.o lmbc.c
In file included from lmbc.c:84:
./lmbc_core.c:324:13: error: implicitly declaring library function 'finite' with type 'int (double)' [-Werror,-Wimplicit-function-declaration]
              if (!LM_FINITE(fpls)) {
                   ^
./compiler.h:63:19: note: expanded from macro 'LM_FINITE'
#define LM_FINITE finite // ICC, GCC
                  ^
./lmbc_core.c:324:13: note: include the header <math.h> or explicitly provide a declaration for 'finite'
./compiler.h:63:19: note: expanded from macro 'LM_FINITE'
#define LM_FINITE finite // ICC, GCC

Based on this thread:
https://github.com/igraph/igraph/issues/1349

changing finite -> isfinite in compiler.h passes. Would this be safe to use on other systems?

**Comment by mcclearyj** [comment]
Just chiming in to say that I also encountered this compiler error (I am running MacOS Monterey on an M2). Thank you for finding this workaround, @mcoughlin.  The suggested change allowed the compilation to run to completion.

**Comment by ebertin** [comment]
Thanks for the heads up! The `finite()` function used in the levmar library is indeed obsolete according to the man page, but it still works on Linux. I have committed a fix in [branch fix/finite](/astromatic/psfex/tree/fix/finite). Would you mind checking that it works (don't have access to a Mac right now)? Thanks.

**Comment by mcoughlin** [comment]
./configure --enable-openblas --with-fftw-libdir=/opt/homebrew/lib/ --with-fftw-incdir=/opt/homebrew/include/ --with-openblas-libdir=/opt/homebrew/opt/openblas/lib/ --with-openblas-incdir=/opt/homebrew/opt/openblas/include/ --with-atlas-libdir=/opt/homebrew/opt/openblas/lib/ --with-atlas-incdir=/opt/homebrew/opt/openblas/include/
and then make on this branch worked. Thanks @ebertin.
