### ISSUE TITLE
version update

### ISSUE THREAD

**Issue by wschoenell** [astromatic/psfex#7]
Dear @ebertin,

Could you create a new release tag with the OpenBLAS support modifications? I am trying to create a Homebrew recipe for installing PSFex in mac, but without it, I would need to do patch outside this repo.

Thanks!

**Comment by ebertin** [comment]
Dear wschoenell,

thank you for reminding me to tag and release more often. I have tagged a new release. And if you can wait another few days, I will merge code improvements I have brought to a private branch, with increased star selection robustness.

**Comment by wschoenell** [comment]
perfect! thanks!

**Comment by jselsing** [comment]
I just want to second, that a homebrew install of PSFex would be magnificent! Big thumbs up for the work!

**Comment by ebertin** [comment]
The new version [has been released](releases/tag/3.21.1)  😇.

**Comment by wschoenell** [comment]
Thanks @ebertin!
